### ISSUE TITLE
PersonalLogistics button ovelays DspGameSpeed UI

### ISSUE THREAD

**Issue by Vladyslav-Krot** [mattsemar/dsp-personal-logistics#1]
I think would be nice to move PersonalLogistics to not overlay DspGameSpeed UI

![Снимок](https://user-images.githubusercontent.com/25057045/135897226-68b69012-9106-476d-abe8-3e5bfbebc2b4.PNG)

Awesome mod, really like it, thanks for the development

**Comment by mattsemar** [comment]
Well I moved it, but I don't love how it looks now. I didn't want to conflict with the mod that dumps out planet resources to a csv file. I remember that it uses that right side for its button.

I may end up just making it a button attached to the inventory window, but for now at least it won't conflict with DspGameSpeed
