### ISSUE TITLE
it doesnt work with foundation i was trying to request foundation from all the hub but nothing fill my inv . i was trying to request from 5 to fill but nothing happened

### ISSUE THREAD

**Issue by mattsemar** [mattsemar/dsp-personal-logistics#14]
it doesnt work with foundation i was trying to request foundation from all the hub but nothing fill my inv . i was trying to request from 5 to fill but nothing happened

_Originally posted by @bosh04011991 in https://github.com/mattsemar/dsp-personal-logistics/issues/13#issuecomment-1003709074_

**Comment by mattsemar** [comment]
@bosh04011991 Can you show a screenshot of the item tooltip that pops up when you mouseover foundation in your inventory (or from replicator)? I just tried this and it worked for me so I'd like to understand what might be happening.

**Comment by mattsemar** [comment]
@bosh04011991 anything else to add to this? I'm going to close the issue if not

**Comment by bosh04011991** [comment]
No issue left everything is working very well thanks for your help and
concerns
