### ISSUE TITLE
v2.5.2 "Item 'X' from [location] is Delayed, Missing Energy in (PLS. ILS)"

### ISSUE THREAD

**Issue by DocHogan** [mattsemar/dsp-personal-logistics#16]
LOVE the new UI! So much easier!

Error: I'm literally standing right next to the only logistics station in my galaxy that has, for example, Sorter Mk III; a PLS in this case. PLS is fully charged, all drones are docked and not consuming energy, and the network it's on is over 100%.. Icarus is full power, and filled with HFRs.

I get this same error (as in Bug Report title) for a LOT of stuff, but I haven't figured out why item 'A' might transfer, but item 'B' might not, with the given error, and, to confuse me more, why item 'C' will give the same message but transfer some (miniscule) part of the requested payload (200 Foundations of a 5000 count transfer, for example)

HELP!

(this is a new issue for 2.5.2, I think; I don't remember having any issue yesterday prior to updating PL)

**Comment by DocHogan** [comment]
Addendum: just also rec'd "is delayed, no warpers in ILS". The ILS is in-system, within 4 AU avg. The ILS is configured to NOT use warpers (tech not unlocked, and not needed in-system).

**Comment by mattsemar** [comment]
> Addendum: just also rec'd "is delayed, no warpers in ILS". The ILS is in-system, within 4 AU avg. The ILS is configured to NOT use warpers (tech not unlocked, and not needed in-system).

Did you actually uncheck Warpers Required on the ILS? That's interesting I would never have thought to try that. 

Edit: or is it that you turned down the distance to enable warp setting?

**Comment by mattsemar** [comment]
Ok so for the "no warpers in ILS" it seems like you may have turned down the "distance to enable" warp setting on the ILS. I tried to make the mod work like the game does and what that setting will do is make the vessels use warpers anytime the distance is greater than the value in the slider. I guess where I went wrong was by not also checking the "Warpers Required" tick.

It seems like I need my own settings that do not rely on how the stations are configured. 

(still checking on the other stuff)

**Comment by DocHogan** [comment]
> > Addendum: just also rec'd "is delayed, no warpers in ILS". The ILS is in-system, within 4 AU avg. The ILS is configured to NOT use warpers (tech not unlocked, and not needed in-system).
> 
> Did you actually uncheck Warpers Required on the ILS? That's interesting I would never have thought to try that.
> 
> Edit: or is it that you turned down the distance to enable warp setting?

Correct, Require Warpers is manually unchecked on all ILSs, and warp distance is set to 12 LY or more (randomly more...I wasn't being precise with the slider; as long as it was above 5 LY, I was satisfied)

EDIT: Just after I posted this reply, I thought "Well, as a troubleshooting step, maybe I should go an put the checkmark in each ILS. Each ILS. All of them. <shudder>". But then I realized that at a couple points I *had* left the checkmark in, and that only kept that ILSs vessels grounded permanently.

**Comment by mattsemar** [comment]
I'm about go offline for a bit, but if you have the inclination here's a [preview of the next version](https://drive.google.com/file/d/1K94MMeRyPpmQXyCDaGU7LsmbCkATnvFq/view?usp=sharing). If you use r2modman you can go to settings and import local file. I still need to check a few things before releasing it, but if it resolves at least 1 issue, I guess it's a win

**Comment by DocHogan** [comment]
> I'm about go offline for a bit, but if you have the inclination here's a [preview of the next version](https://drive.google.com/file/d/1K94MMeRyPpmQXyCDaGU7LsmbCkATnvFq/view?usp=sharing). If you use r2modman you can go to settings and import local file. I still need to check a few things before releasing it, but if it resolves at least 1 issue, I guess it's a win

Past my bedtime, but I'll give it runthrough tomorrow :) And, yes, I use r2modman. One nice thing about it is that it keeps mods up to date, which is why I think that whatever is going on happened only started with 2.5.2, as I've remained current.

**Comment by mattsemar** [comment]
Ok, I think the new version may address some of these issues. I found a few places where I was assuming the mod would be used only in the very late game (fully upgraded vessel capacity for example). Let me know if it works better

**Comment by mattsemar** [comment]
Please re-open or open a new issue if you're still running into this issue. From what I can tell it's fixed
