### ISSUE TITLE
What's Different Between AnySupply and IlsDemandRules？

### ISSUE THREAD

**Issue by zxcvbnm3057** [mattsemar/dsp-personal-logistics#17]

**Comment by zxcvbnm3057** [comment]
I use the default setting(IlsDemandRules) in my game, but still items form other planet comming into my inventory. Even if I am in a universally traveling. Which mode should I choose if I want to auto get items from the very planet I am landed? And what is  the buffer mean. Is that why I can still get items on a travel? Thx!

**Comment by mattsemar** [comment]
IlsDemandRules work just like an ILS sitting next to set to LocalDemand/RemoteDemand would work. So, you can get items from other planets if they are in an ILS that is set to RemoteSupply. I don't really have a mode for local planet only, but I suppose I could add it.

There's more about the buffer in the readme, but it seems like this part might answer what you are wanting to know
https://github.com/mattsemar/dsp-personal-logistics#numerical-indicator-faq

**Comment by zxcvbnm3057** [comment]
Thanks for your reply. So could you please add a mode for local planet only? And the FAQ doesn't seem to help. I mean that whether I still get items form ILS and PLS on a universal travel because of the buffer or because I get them from PLS directly? I want to get items from the ILS and PLS only if I am landed on the planet but never could get them while I am on sail or the station and I are not on the same planet.

**Comment by mattsemar** [comment]
The readme also has a [Request Modes](https://github.com/mattsemar/dsp-personal-logistics#request-modes) section and a section about what the [Buffer](https://github.com/mattsemar/dsp-personal-logistics#buffer) is. 

I'm testing out a change to only do shipping from the local planet, but as you may have guessed, items that are already in your local buffer would still be used to replenish your inventory

**Comment by zxcvbnm3057** [comment]
yeah, I noticed it too. So is there any options to disable the buffer? So there wouldn't be any accident. And in that way, maybe add an callback for open and close inventory and do the requests will be a better solutions.

**Comment by zxcvbnm3057** [comment]
In fact, I just want to use it instead of manually opening the stations on the planet to access items. There is always too many towers.

**Comment by mattsemar** [comment]
It's not an accident. It's just the way the mod works. 

1. For each requested item, the desired amount is compared with the amount you have in your inventory.
2. If your inventory is short, we look in buffer to see if the item is there. If item is in your buffer then it gets added to your inventory (< 5 seconds)
3. If no items are in your buffer, then 1,000 (or fewer there aren't 1k available) worth are shipped to your buffered area from your logistics network. This is where the Request Modes come into play and this part is what takes time depending on how far away the item is.
4. Items from buffer are loaded to your inventory

It's done this way to reduce the cost of shipping stuff to you. So, if you are, for example, adding a long belt, well the game is taking 1 belt from your inventory at a time. Well if every time a belt is removed from your inventory you had to pay shipping costs to get 1 more that really adds up.

**Comment by mattsemar** [comment]
> In fact, I just want to use it instead of manually opening the stations on the planet to access items. There is always too many towers.

So you really want shipping from local planet, but done instantly?

**Comment by zxcvbnm3057** [comment]
yes, that is what I want. But after all, you are the author LOL. So just do it in your way.

btw, I think ship from anywhere is kind of break the balance. In my situation, I just want a mod to release myself from the station blur.

**Comment by zxcvbnm3057** [comment]
In a sense, buffer is equivalent to expanding the inventory, and get items wherever I am whithout a station? That is cool but lost interest in planning a travel

**Comment by mattsemar** [comment]
> btw, I think ship from anywhere is kind of break the balance. In my situation, I just want a mod to release myself from the station blur.

If you mean `AnySupply` then I agree and it's why it's not the default any longer. I really just keep it around for backward compatibility.

If you also include `IlsDemandRules` then I don't really agree. It's not that much different than a player putting down an ILS and requesting the stuff they want and waiting. It just automates those steps (still uses warpers and energy)

**Comment by zxcvbnm3057** [comment]
yes, I know that because the warpers in my inventory keep costing. That's way I use the word "kind of".

**Comment by zxcvbnm3057** [comment]
"way" means "why", my fault

**Comment by mattsemar** [comment]
> In a sense, buffer is equivalent to expanding the inventory, and get items wherever I am whithout a station? That is cool but lost interest in planning a travel

Yes it is like an expanded inventory, or maybe it's like carrying a chest around with you in your inventory. BTW, I'm testing to see how it would work if the buffer is bypassed in this new `PlsDemandRules` mode.

**Comment by zxcvbnm3057** [comment]
With all due respect, this method may not work well. If I cost one of each requested items.Is will ship for each item for one time. Maybe there is a delay to accumulate but still a not that perfect solution.

**Comment by mattsemar** [comment]
> With all due respect, this method may not work well. If I cost one of each requested items.Is will ship for each item for one time. Maybe there is a delay to accumulate but still a not that perfect solution.

You're right about that, I was just experimenting with other options (like returning all buffered items to stations when you leave a planet or only deliver from buffer if planet has the item in your buffer)

**Comment by zxcvbnm3057** [comment]
On these conditions, I think this might be the best.><

> In fact, I just want to use it instead of manually opening the stations on the planet to access items. There is always too many towers.

**Comment by mattsemar** [comment]
I just uploaded a new version to the store that adds the Planetary request mode.

**Comment by zxcvbnm3057** [comment]
Thanks, but I haven't had time to try...
