### ISSUE TITLE
v2.6.2 nullreferenceexception on game start

### ISSUE THREAD

**Issue by Issytia** [mattsemar/dsp-personal-logistics#19]
Since the recent updates of the game and the plugin, I get this exception repeatedly on game start.

![immagine](https://user-images.githubusercontent.com/44508492/150649589-c3314f21-6d42-467d-8cae-9ba316a26e3a.png)

I've tried disabling other mods, removing save data, and changing the nebula user id in the config, but no luck.
Not sure what else to try.

My r2modman code is TOCdFIqCCu.

I'm running the game through Proton 7.0rc3_GE_1.

**Comment by mattsemar** [comment]
I have a guess as to what my be causing this. Do you happen to see anything like this in the logs?

```
ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
```

**Comment by Issytia** [comment]
![immagine](https://user-images.githubusercontent.com/44508492/150675532-3be3d5a9-671d-43b2-a44d-d72a709cb033.png)

Again not in any log files. 🤔

With mods updated I can at least get into the game again.

**Comment by mattsemar** [comment]
I think was caused by LDBTool, and I think with the latest version it won't happen anymore

**Comment by mattsemar** [comment]
Please re-open if you're still seeing this issue
