### ISSUE TITLE
Status text placement

### ISSUE THREAD

**Issue by Cringely** [mattsemar/dsp-personal-logistics#20]
**Describe the bug**
Status text is off screen. This seems to have started immediately after following the most recent major game update.

**To Reproduce**
1. Install mod with mod manager
2. Run game

**Expected behavior**
Readable status text

**Screenshots**
![image](https://user-images.githubusercontent.com/759077/150696961-21958771-a041-459a-82ca-34c0a174778d.png)

**Mods installed**
jaYzZWjA0a

**Extra**
Unable to upload save and mod save data after trying to ZIP and upload.

**Comment by mattsemar** [comment]
Out of curiosity, what resolution are you using? Also is the "UI layout resolution reference height" (in Settings->Gameplay) different than the resolution's height?

**Comment by Cringely** [comment]
This is 2560x1440p with a reference height of 900. This worked just fine prior to update, however with that being said I did also forget my reference height was so low (I enjoy the larger UI elements).

For now I've set the reference height to 1080 and everything is correctly visible again. I'd still appreciate using 900 but also don't mind just using 1080 as a workaround for this.

Thanks for your time. Feel free to close this, due to this reference heigh workaround :)

**Comment by mattsemar** [comment]
I'm definitely going to fix it, I'm just compiling a list of resolutions and ref heights to test before I release versions.

**Comment by mattsemar** [comment]
I think this should be fixed with the release from yesterday

**Comment by Cringely** [comment]
Confirming this appears to be resolved. Thanks for your support!
