### ISSUE TITLE
Does not recycle to logistics systems

### ISSUE THREAD

**Issue by Uniform300** [mattsemar/dsp-personal-logistics#29]
**Describe the bug**
When I set any item to "recycle" in the mod UI the items just disappear from my inventory and do not reappear in any logistic station

**To Reproduce**
1. Set an item to "recycle" to the logistics station if more than x amount 
2. Remove more than x amount of any item from a station and put it into personal inventory
3. It just disappears from the inventory but does not appear in the station 
4. I have a video of it happening but Github doesn't support video attachment

**Comment by mattsemar** [comment]
Recycled items aren't immediately added to stations. They sit in the buffer for 60 seconds before they get sent to stations. This is in case more items are added to your inventory (like when tearing down a large factory). You should be able to see the recycled item in Buffered Items section of the Legacy UI. There you can also see the age of the item. If after 60 seconds the item is no longer in the buffer and is not in any station then yes, that is a bug.

**Comment by mattsemar** [comment]
@Uniform300 can you confirm that even after 60 seconds the item is still not added to stations?

**Comment by mattsemar** [comment]
I'm closing this one. I lowered the time it takes before recycled items are sent to stations to 15 seconds
