### ISSUE TITLE
Arrival text covers Research tasks

### ISSUE THREAD

**Issue by ghostorchidgaming** [mattsemar/dsp-personal-logistics#3]
Just a small inconvience, but the arrival countdown text covers the research tasks. My resulution is 2560x1440.  But looking at the code I think changing the x,y (100,100) here should fix it https://github.com/mattsemar/dsp-personal-logistics/blob/9392dc1b5be4941542cabe1ea5da61adcaf588c3/TimeScript.cs#L36

![20211012133617_1](https://user-images.githubusercontent.com/79421462/137059878-98d41cd2-b425-4876-bc07-a9336d16ca1d.jpg)

**Comment by mattsemar** [comment]
Ah that's interesting, I'm still living in the past with 1920x1080. I'll see if I can maybe do something a little smarter

**Comment by Wolphin5** [comment]
I am also having an issue with where it places the text.

I am running in a window 1920x1080.  I would love to be able to turn on and off the text, but mostly it's an annoyance, as it stays on top of everything!

Covers the manual research window:
![image](https://user-images.githubusercontent.com/44385601/137244911-d31e71bc-2879-4dd2-80f7-11944f594e34.png)

I have the DSPAllPlanetInfo by appuns plugin, and it covers the info of what the interstellar logistics has:
![image](https://user-images.githubusercontent.com/44385601/137245051-7efa3de4-c28b-414e-a79f-0424011fe2c8.png)

**Comment by mattsemar** [comment]
Ok, I just released a new version. 1.0.8. You can now turn off the incoming items text and I added something to hide the text when the star map, globemap or escape menu are open.

**Comment by mattsemar** [comment]
All right, I believe this is really fixed now, as of v1.0.9. Please let know if that's not the case. 

Also, thanks for the bug reports
