### ISSUE TITLE
DSP Crashes upon PL start

### ISSUE THREAD

**Issue by Sortileger** [mattsemar/dsp-personal-logistics#31]
Since the last update, my game crashes on startup when loading PL.  I tried deleting the .cfg file and restarting, but it crashes before it writes a new file.  Everything is fine as long as I disable PL.
![PXL_20220421_181212846](https://user-images.githubusercontent.com/76822414/164526654-a915e01b-faca-4384-83a9-f59010e03f8a.jpg)

**Comment by Sortileger** [comment]
If I can help in any way, just let me know.

**Comment by mattsemar** [comment]
Looks like that error is coming from a different mod. https://dsp.thunderstore.io/package/appuns/DSPAllPlanetInfo

**Comment by brianorca** [comment]
![image](https://user-images.githubusercontent.com/104186438/164608485-634c5f1e-5ee9-45a3-8b8b-875cc01b626e.png)
I'm getting this error with PL. I do NOT have DSPAllPlanetInfo.
It started with the 4/21 version of DSP which just released.

**Comment by mattsemar** [comment]
Hi @brianorca, have you tried the patched version of Common API? I'm pretty sure the error you linked is not related to Personal Logistics, but if it is, I'll definitely fix it

https://discord.com/channels/@me/966879863556431882/966892306055700511

**Comment by Sortileger** [comment]
> Looks like that error is coming from a different mod. https://dsp.thunderstore.io/package/appuns/DSPAllPlanetInfo

I removed that mod and everything is working so far.  Thank you!!

**Comment by brianorca** [comment]
CommonAPI didn't have that update yesterday. It seems to work now.
