### ISSUE TITLE
got an error 

### ISSUE THREAD

**Issue by freeseacher** [mattsemar/dsp-personal-logistics#32]
**Describe the bug**
big red error appears when nothing special was done

**To Reproduce**
1. went to dyson sphere screen and get this error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/289277/164894481-22f64d54-7ec3-47b6-aaff-b2c8e73f7ad1.png)

**Mods installed**
MalLDNzuHY 

**Extra**
Bonus points if you include the save and mod save files to make reproducing easier. These can be found in Documents\Dyson Sphere Program\Save

**Comment by AnysSido** [comment]
I'm also receiving this error whenever I delete a PLS that causes items to fall to the floor that then get auto-recycled.

**Comment by mattsemar** [comment]
Ok thanks, I'll take a look

**Comment by mattsemar** [comment]
I think this should be fixed in the 2.9.3 version I just uploaded. If not, either re-open this issue or open a new one
