### ISSUE TITLE
Allow a block list for fuels

### ISSUE THREAD

**Issue by ThePiercedPrince** [mattsemar/dsp-personal-logistics#36]
My feature request is that I would like to not burn Organic Crystals, Nanotubes, etc as fuel automatically.  I gather these things from resources early on and end up if I'm not paying attention burning them when I run out of other combustibles.  This obviously isn't ideal.  I absolutely love the not having to think about dealing with fuel as long as I have some available somewhere.  But, certain fuels I feel should be exempt.

If I can ban items from being in my inventory at all, I would like to be able to ban specific fuels as well.

**Comment by mattsemar** [comment]
Ok I added support for this in 2.9.7
