### ISSUE TITLE
Extremely long delivery times

### ISSUE THREAD

**Issue by tivec** [mattsemar/dsp-personal-logistics#6]
![image](https://user-images.githubusercontent.com/717574/140355001-5b345f64-9cc4-4a71-8fb2-f1e00feec375.png)

I went flying to space and ended up with the above. That's about 4.7 hours real time. It'd be good to have a way to limit the max delivery "range", or time. I can't find a way to cancel those, so it's a bit of a hassle...

**Comment by mattsemar** [comment]
This looks like a good one, thanks for the report.  I was curious if you're using the default Station Request Mode ("All"), or is it custom? Also, if you see it again, could you try and grab the log file at: `%USERPROFILE%\AppData\LocalLow\Youthcat Studio\Dyson Sphere Program\output_log.txt` 

I've got a few ideas, though, but I might just push out a feature to let you cancel inbound requests until I think I have a good solution.

**Comment by mattsemar** [comment]
Ok, I think I figured this one out. Should have a fix published in a bit

**Comment by mattsemar** [comment]
All right, this should be resolved now. I also added a cancel requests action as well as a config for the max time wait for items to be delivered. Thanks again for letting me know about this, please let me know if the change I made doesn't resolve the issue.

**Comment by tivec** [comment]
> I was curious if you're using the default Station Request Mode ("All")

Correct, I hadn't changed anything in the settings. Thanks for looking at this and adding a cancel requests action and config :) That should help me LOTS.
