### ISSUE TITLE
Best mod out there!

### ISSUE THREAD

**Issue by Quentin-M** [mattsemar/dsp-personal-logistics#9]
Just wanted to share my appreciation for this mod - it is without contest the best QoL mode of there..! Automatically topping up from mall removes the single most painful element of the game - constantly going back and forth or having to deal with mall towers..! (Also your README is fantastic!)

**Comment by mattsemar** [comment]
Wow, thank you very much. That's very kind. I just released a pretty big change to the UI so hopefully you still feel the same after version 2.

**Comment by Quentin-M** [comment]
It looks actually fantastic, and I love the fact that you also kept the legacy UI around as a backup in case there is an issue or just preferred. 💯 I also noted the notification about incoming flight with the ETA, good stuff~
